apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# CD pipeline will run `kustomize edit set image` on this overlay to pin
# a specific SHA before applying.
images:
  - name: flashlearn-app
    newName: ghcr.io/fyzhang66/flashlearn
    newTag: latest
