[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    Parsers_File  parsers.conf

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224
    Tag           docker.*

[FILTER]
    Name          modify
    Match         *
    Add           service.name flashlearn

[OUTPUT]
    Name              es
    Match             *
    Host              elasticsearch
    Port              9200
    Index             fluentbit
    Logstash_Format   On
    Logstash_Prefix   fluentbit
    Suppress_Type_Name On
    Retry_Limit       5
